name: snowflake-devops-QA

# Controls when the action will run. 
on:
  pull_request:
   branches:
    - "QA"
   types: [closed]
   
   paths:
      - 'Migrations/**'

  # Allows you to run this workflow manually from the Actions tab
jobs:              
    deploy-snowflake-changes-job:
      runs-on: ubuntu-latest
    
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_QA_USERNAME: ${{ secrets.SF_QA_USERNAME }}
          SF_QA_ROLE: ${{ secrets.SF_QA_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_QA_DB: ${{ secrets.SF_QA_DB }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_QA_PASSWORD }}
          ENV_WH: ${{ secrets.QA_ENV_WH }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/Migrations -a $SF_ACCOUNT -u $SF_QA_USERNAME -r $SF_QA_ROLE -w $SF_WAREHOUSE -d $SF_QA_DB -c $SF_QA_DB.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
